library(shiny)
library(shinydashboard)
library(shinythemes)
library(dashboardthemes)
library(slickR)
library(DT)
library(ggplot2)
library(multicolor)
library(ggnetwork)
library(shinycssloaders)
library(shinycustomloader)
library(htmltools)
library(htmlwidgets)
ui<-dashboardPage(skin = "yellow",
  dashboardHeader( title=shinyDashboardLogo(theme = "poor_mans_flatly",boldText = "NEGLATED",mainText = "DIS",badgeText = "DB"),tags$li(class="dropdown",tags$a("DEVELOPER",icon("male"),target="_blank")),dropdownMenuOutput("msgoutput"),
                   dropdownMenu(type = "message",
                                messageItem(from = "website","any one want to create web application contact me"),
                                messageItem(from = "updates","website update")),
                   dropdownMenu(type = "notification",
                                notificationItem(text = "error network connecion",
                                                 icon = icon("warning"),
                                                 status = "warning")),
                   dropdownMenu(type = "task",
                                taskItem(value = 80,
                                         color = "green",
                                         "ovrall"))),
  dashboardSidebar(
    sidebarUserPanel("DASHBOARD",image = "123.jpg"),
    sidebarMenu(menuItem("HOME",tabName = "HOME",icon = icon("home"),badgeLabel = "new",badgeColor = "purple"),
                menuItem("AFFECTS",tabName = "AFFECTS",icon = icon("th"),badgeLabel = "people effects",badgeColor = "aqua"),
                menuItem("DISEASE",tabName = "DISEASE",icon = icon("desktop"),badgeLabel = "information",badgeColor = "lime" ),
                menuItem("ORGANISM",tabName = "ORGANISM",icon = icon("bug"),badgeLabel = "disease causes",badgeColor = "red"),
                menuItem("CONTROL",tabName = "CONTROL",icon = icon("cogs"),badgeLabel = "disease",badgeColor = "yellow"),
                menuItem("TARGETS",tabName = "TARGETS",icon = icon("eye"),
                         menuSubItem("buruli_ulcer",tabName = "buruli_ulcer",icon = icon("eye")),
                         menuSubItem("chagas_disease",tabName = "chagas_disease",icon = icon("eye")),
                         menuSubItem("dengue",tabName = "dengue",icon = icon("eye")),
                         menuSubItem("dracunculiasis_disease",tabName = "dracunculiasis_disease",icon = icon("eye")),
                         menuSubItem("echinococcosis_disease",tabName = "echinococcosis_disease",icon = icon("eye")),
                         menuSubItem("fascilolisis",tabName = "fascilolisis",icon = icon("eye")),
                         menuSubItem("foodbrone",tabName = "foodbrone",icon = icon("eye")),
                         menuSubItem("humanafrican_trypanosomiasis",tabName = "humanafrican_trypanosomiasis",icon = icon("eye")),
                         menuSubItem("leishmaniasies",tabName = "leishmaniasies",icon = icon("eye")),
                         menuSubItem("leprosy",tabName = "leprosy",icon = icon("eye")),
                         menuSubItem("lymphatic_filariasis",tabName = "lymphatic_filariasis",icon = icon("eye")),
                         menuSubItem("mycetoma",tabName = "mycetoma",icon = icon("eye")),
                         menuSubItem("onchocerciasis",tabName = "onchocerciasis",icon = icon("table")),
                         menuSubItem("rabies",tabName = "rabies",icon = icon("eye")),
                         menuSubItem("schistosomiasis",tabName = "schistosomiasis",icon = icon("eye")),
                         menuSubItem("soil_transmitted_helminthises",tabName = "soil_transmitted_helminthises",icon = icon("eye")),
                         menuSubItem("trachoma",tabName = "trachoma",icon = icon("table")),
                         menuSubItem("yaws",tabName = "yaws",icon = icon("eye")),
                         menuSubItem("neurocysticercosis",tabName = "neurocysticercosis",icon = icon("eye"))),
                menuItem("GENES",tabName = "data",icon = icon("dna"),
                         menuSubItem("Buruli_Ulcer",tabName = "Buruli_Ulcer",icon = icon("list-alt")),
                         menuSubItem("Dengue",tabName = "Dengue",icon = icon("list-alt")),
                         menuSubItem("Rabies",tabName = "Rabies",icon = icon("list-alt")),
                         menuSubItem("Trachoma",tabName = "Trachoma",icon = icon("list-alt")),
                         menuSubItem("Yaws",tabName = "Yaws",icon = icon("list-alt")),
                         menuSubItem("Leprosy",tabName = "Leprosy",icon = icon("list-alt")),
                         menuSubItem("Chagasdisease",tabName = "Chagasdisease",icon = icon("list-alt")),
                         menuSubItem("Human_African_trypanosomiasis",tabName = "Human_African_trypanosomiasis",icon = icon("list-alt")),
                         menuSubItem("Leishmaniases",tabName = "Leishmaniases",icon = icon("list-alt")),
                         menuSubItem("Taeniasis_and_neurocysticercosis",tabName = "Taeniasis_and_neurocysticercosis",icon = icon("list-alt")),
                         menuSubItem("Dracunculiasis",tabName = "Dracunculiasis",icon = icon("list-alt")),
                         menuSubItem("Foodborne_trematodiases",tabName = "Foodborne_trematodiases",icon = icon("list-alt")),
                         menuSubItem("Echinococcosis",tabName = "Echinococcosis",icon = icon("list-alt")),
                         menuSubItem("Lymphatic_filariasis",tabName = "Lymphatic_filariasis",icon = icon("list-alt")),
                         menuSubItem("Onchocerciasis",tabName = "Onchocerciasis",icon = icon("list-alt")),
                         menuSubItem("Schistosomiasis",tabName = "Schistosomiasis",icon = icon("list-alt")),
                         menuSubItem("Soil-transmitted-helminthiases",tabName = "Soil-transmitted-helminthiases",icon = icon("list-alt")),
                         menuSubItem("Mycetoma",tabName = "Mycetoma",icon = icon("list-alt")),
                         menuSubItem("Fascilolisis",tabName = "Fascilolisis",icon = icon("list-alt"))),
                menuItem("NETWORK",tabName = "NETWORK",icon = icon("line-chart"),badgeLabel = "Genes",badgeColor = "lime"),
              menuItem("CONTACTS",tabName = "CONTACTS",icon = icon("phone"),badgeLabel = "develop",badgeColor = "purple"),
              menuItem("Whatsapp",tabName = "Whatsapp",icon = icon("whatsapp"),badgeLabel = "chat",badgeColor = "aqua"),
              menuItem("Facebook",tabName = "Facebook",icon = icon("facebook"),badgeLabel = "chat",badgeColor = "red")
    
  )),
  dashboardBody(
    tabItems(
      tabItem("HOME",infoBox("DISEASE INFORMATION",icon = icon("wpexplorer")),infoBox("CONTROL",icon = icon("plus-square")),infoBox("SMALL MOLECULE",icon = icon("table")),infoBox("GENES LIST",icon = icon("info-circle")),infoBox("BAR CHARTS",icon = icon("bar-chart")),infoBox(" DISEASE EFFECTS 149COUNTRIES",icon = icon("warning")),tags$h4("NEGELATED DISDB:Neglected disease,are group of disease
                                                                                                                                                                                      that occur under tropical and sub-tropical climate conditions and are intimately linked to poverty.They therefore thrive in area where access to adequate sanitation, clean water and healthcare is limited, and people
                                                                                                                                                                                      live in proximity with animals and infective disease vectors, such as in remote and rural areas,informal settlements (or) conflict zones.Neglected disease affect some of the world poorest and most marginalize communities
                                                                                                                                                                                      predominantly in africa,asia and the americans.This database present in general information,organism,genes,Network plots ,symptoms and control."),tags$img(src="1.jpg",height="200px",width="320px"),tags$img(src="3.jpg",height="200px",width="330px"),tags$img(src="2.jpg",height="200px",width="320px")),
      
      tabItem("AFFECTS",valueBox(5000,"Buruli Ulcer(people)"),valueBox(390,"Dengue(million)"),valueBox(3,"Rabies (Million)"),
              valueBox(80,"Trachoma(million)",color = "lime"),valueBox(5,"Yaws(laks)",color = "lime"),valueBox(180000,"Leprosy",color = "lime"),
              valueBox(7,"Chagas disease(Million)",color = "orange"),valueBox(70000,"Human African trypanosomiasis(million)",color = "orange"),valueBox(12,"Leishmaniases(Million)",color = "orange"),
              valueBox(2.5,"Taeniasis and neurocysticercosis(million)",color = "purple"),valueBox(54,"Dracunculiasis",color = "purple"),valueBox(2,"Foodborne trematodiases(millions)",color = "purple"),
              valueBox(1,"Echinococcosis(billion)",color = "lime"),valueBox(120,"Lymphatic filariasis(million)",color = "lime"),valueBox(18,"Onchocerciasis(million)",color = "lime"),
              valueBox(200,"Schistosomiasis(million)",color = "yellow"),valueBox(1.5,"Soil-transmitted helminthiases(Billion )",color = "yellow"),valueBox(8763,"Mycetoma",color = "yellow"),valueBox(2.4,"Fascilolisis(million)",color = "green")),
      tabItem("DISEASE",withLoader(dataTableOutput("table1"),type = "html",loader = "dnaspin")),
      tabItem("ORGANISM",dataTableOutput("table2"),withLoader(plotOutput("plot222"),type = "html",loader = "pacman")),
      tabItem("CONTROL",withLoader(dataTableOutput("table3"),type = "html",loader = "pacman")),
      tabItem("TARGETS"),
      tabItem("buruli_ulcer",withLoader(dataTableOutput("tab1"),type = "html",loader = "pacman"),br(),tags$h5("any updates for Targets search Chembel database")),
      tabItem("chagas_disease",withLoader(dataTableOutput("tab2"),type = "html",loader = "pacman"),br(),tags$h5("any updates for Targets search Chembel database")),
      tabItem("dengue",withLoader(dataTableOutput("tab3"),type = "html",loader = "pacman"),br(),tags$h5("any updates for Targets search Chembel database")),
      tabItem("dracunculiasis_disease",withLoader(dataTableOutput("tab4"),type = "html",loader = "pacman"),br(),tags$h5("any updates for Targets search Chembel database")),
      tabItem("echinococcosis_disease",withLoader(dataTableOutput("tab5"),type = "html",loader = "pacman"),br(),tags$h5("any updates for Targets search Chembel database")),
      tabItem("fascilolisis",withLoader(dataTableOutput("tab6"),type = "html",loader = "pacman"),br(),tags$h5("any updates for Targets search Chembel database")),
      tabItem("foodbrone",withLoader(dataTableOutput("tab7"),type = "html",loader = "pacman"),br(),tags$h5("any updates for Targets search Chembel database")),
      tabItem("humanafrican_trypanosomiasis",withLoader(dataTableOutput("tab8"),type = "html",loader = "pacman"),br(),tags$h5("any updates for Targets search Chembel database")),
      tabItem("leishmaniasies",withLoader(dataTableOutput("tab9"),type = "html",loader = "pacman"),br(),tags$h5("any updates for Targets search Chembel database")),
      tabItem("leprosy",withLoader(dataTableOutput("tab10"),type = "html",loader = "pacman"),br(),tags$h5("any updates for Targets search Chembel database")),
      tabItem("lymphatic_filariasis",withLoader(dataTableOutput("tab11"),type = "html",loader = "pacman"),br(),tags$h5("any updates for Targets search Chembel database")),
      tabItem("mycetoma",withLoader(dataTableOutput("tab12"),type = "html",loader = "pacman"),br(),tags$h5("any updates for Targets search Chembel database")),
      tabItem("onchocerciasis",withLoader(dataTableOutput("tab13"),type = "html",loader = "pacman"),br(),tags$h5("any updates for Targets search Chembel database")),
      tabItem("rabies",withLoader(dataTableOutput("tab14"),type = "html",loader = "pacman"),br(),tags$h5("any updates for Targets search Chembel database")),
      tabItem("schistosomiasis",withLoader(dataTableOutput("tab15"),type = "html",loader = "pacman"),br(),tags$h5("any updates for Targets search Chembel database")),
      tabItem("Soil-transmitted-helminthiases",withLoader(dataTableOutput("tab16"),type = "html",loader = "pacman"),br(),tags$h5("any updates for Targets search Chembel database")),
      tabItem("trachoma",withLoader(dataTableOutput("tab17"),type = "html",loader = "pacman"),br(),tags$h5("any updates for Targets search Chembel database")),
      tabItem("yaws",withLoader(dataTableOutput("tab18"),type = "html",loader = "pacman"),br(),tags$h5("any updates for Targets search Chembel database")),
      tabItem("neurocysticercosis",withLoader(dataTableOutput("tab19"),type = "html",loader = "pacman"),br(),tags$h5("any updates for Targets search Chembel database")),
      tabItem("GENES"),
      tabItem("Buruli_Ulcer",withLoader(dataTableOutput("Buruli_Ulcer"),type = "html",loader = "dnaspin"),br(),plotOutput("plot1")),
      tabItem("Dengue",withLoader(dataTableOutput("Dengue"),type = "html",loader = "dnaspin"),br(),plotOutput("plot2")),
      tabItem("Rabies",withLoader(dataTableOutput("Rabies"),type = "html",loader = "dnaspin"),br(),plotOutput("plot3")),
      tabItem("Trachoma",withLoader(dataTableOutput("Trachoma"),type = "html",loader = "dnaspin"),br(),plotOutput("plot4")),
      tabItem("Yaws",withLoader(dataTableOutput("Yaws"),type = "html",loader = "dnaspin"),br(),plotOutput("plot5")),
      tabItem("Leprosy",withLoader(dataTableOutput("Leprosy"),type = "html",loader = "dnaspin"),br(),plotOutput("plot6")),
      tabItem("Chagasdisease",withLoader(dataTableOutput("Chagasdisease"),type = "html",loader = "dnaspin"),br(),plotOutput("plot19")),
      tabItem("Human_African_trypanosomiasis",withLoader(dataTableOutput("Human_African_trypanosomiasis"),type = "html",loader = "dnaspin"),br(),plotOutput("plot7")),
      tabItem("Leishmaniases",withLoader(dataTableOutput("Leishmaniases"),type = "html",loader = "dnaspin"),br(),plotOutput("plot8")),
      tabItem("Taeniasis_and_neurocysticercosis",withLoader(dataTableOutput("Taeniasis_and_neurocysticercosis"),type = "html",loader = "dnaspin"),br(),plotOutput("plot9")),
      tabItem("Dracunculiasis",withLoader(dataTableOutput("Dracunculiasis"),type = "html",loader = "dnaspin"),br(),plotOutput("plot10")),
      tabItem("Foodborne_trematodiases",withLoader(dataTableOutput("Foodborne_trematodiases"),type = "html",loader = "dnaspin"),br(),plotOutput("plot11")),
      tabItem("Echinococcosis",withLoader(dataTableOutput("Echinococcosis"),type = "html",loader = "dnaspin"),br(),plotOutput("plot12")),
      tabItem("Lymphatic_filariasis",withLoader(dataTableOutput("Lymphatic_filariasis"),type = "html",loader = "dnaspin"),br(),plotOutput("plot13")),
      tabItem("Onchocerciasis",withLoader(dataTableOutput("Onchocerciasis"),type = "html",loader = "dnaspin"),br(),plotOutput("plot14")),
      tabItem("Schistosomiasis",withLoader(dataTableOutput("Schistosomiasis"),type = "html",loader = "dnaspin"),br(),plotOutput("plot15")),
      tabItem("Soil-transmitted-helminthiases",withLoader(dataTableOutput("Soil_transmitted_helminthiases"),type = "html",loader = "dnaspin"),br(),plotOutput("plot16")),
      tabItem("Mycetoma",withLoader(dataTableOutput("Mycetoma"),type = "html",loader = "dnaspin"),br(),plotOutput("plot17")),
      tabItem("Fascilolisis",withLoader(dataTableOutput("Fascilolisis"),type = "html",loader = "dnaspin"),br(),plotOutput("plot18")),
      tabItem("NETWORK",withLoader(plotOutput("chart1"),type = "html",loader = "pacman"),plotOutput("chart2"),plotOutput("chart3"),plotOutput("chart4"),plotOutput("chart5"),plotOutput("chart6"),plotOutput("chart7"),
              plotOutput("chart8"),plotOutput("chart9"),plotOutput("chart10"),plotOutput("chart11"),plotOutput("chart12"),plotOutput("chart13"),plotOutput("chart14"),plotOutput("chart15"),
              plotOutput("chart16"),plotOutput("chart17"),plotOutput("chart18"),plotOutput("chart19")),
      tabItem("CONTACTS",tags$img(src="123.png",height="500px",width="800px")),
      tabItem("Whatsapp",tags$h4("Venu Paritala, Whatsaap No:7799509079,web appliction Developer ")),
      tabItem("Facebook",tags$h4("my Facebook id: Venu paritala (Vignan University,Guntur)"))))
    )
  
